#TODO 1: Sa startez o baza de date de tip mysql din compose
version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: reactlibrarydatabase
      # MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db
      
networks:
  my-network:


volumes:
  mysql-data:

    # docker-compose up

    #TODO 2: De startat backed pentru a se conecta la baza de date de mai sus
    #TODO 3: De facut un docker file pentru backend si de facut manual docker run si docker build
    #TODO 4: Sa integrezimaginea de backend in docker compose (build sa se faca folosing dockerfile din backend)
    #TODO 5: De creat un network in care sa fie baza de date si bakendul si de verificat daca backendul reuseste sa se conecteze la baza de date
    #TODO 6: De facut un docker file pentru frontend si de pus in aceeasi retea si de verificat dace backendul se conecteaza la frontend
