#TODO 1: Sa startez o baza de date de tip mysql din compose
version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: reactlibrarydatabase
      # MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - db
      - backend
      
networks:
  my-network:


volumes:
  mysql-data:

    # docker-compose up

    #TODO 6: De facut un docker file pentru frontend si de pus in aceeasi retea si de verificat dace backendul se conecteaza la frontend
    #TODO 7: make the data to persist after restart